source 'https://rubygems.org'

gem 'json'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'unicorn'
gem 'aws-sdk'
gem 'capistrano'
#gem 'capistrano-rbenv'
gem 'capistrano-bundler'
gem 'capistrano3-unicorn'

gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord'
